# Test publishing to, and installing and running with Test PyPI

name: Install & test TestPyPI package
on:
  workflow_dispatch:

jobs:
  # Install geedim from Test PyPI and test CLI
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install geedim from Test PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --extra-index-url https://test.pypi.org/simple/ geedim==${{ github.event.release.tag_name[1:] }}
      - name: Test geedim CLI
        timeout-minutes: 5
        env:
          EE_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.EE_SERVICE_ACC_PRIVATE_KEY }}
        run: |
          geedim search -c landsat8-c2-l2 -s 2019-02-01 -e 2019-03-01 --bbox 23 -33 23.2 -33.2 composite -cm q-mosaic --mask download --scale 30 --crs EPSG:3857 -o
          test -f ./data/test_example/homogenised/3324c_2015_1004_05_0182_RGB_HOMO_cREF_mGAIN-BLK-OFFSET_k5_5.tif && echo "Test OK"
          pwd
          ls -R
